[package]
name = "aoc2021"
version = "0.1.0"
authors = ["Pieter van den Ham <p.e.vandenham@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.0"
num-traits = "0.2.14"
ndarray = "0.15.4"